apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector: # specifies on which pod the configurations will be invoked. if the pod label matches by app value then it will apply the configuration on that pod.
    app: myapp
  ports:
  - port: 80 # specifie on which port the service listens for the incoming traffic from the external sources
    targetPort: 8080  # specify on which port the pod is listening
    protocol: TCP # specifie the network protocol such as TCP, UDP, etc
